spring:
    application:
        name: RevTrivia
        security:
            jwt:
                secret-key: yElziV/vC0Jc3Qos8+m/P+bB3e6zF5DLmUTxLyvaPBXfVh/BbYqiQCD0Y31Rzijl
                expiration: 30000 # 30 sec
                refresh-token:
                    expiration: 604800000 # 7 days
    # PostgreSQL DB
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    jpa:
        database: POSTGRESQL
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        # create-drop means the database is fresh on each restart
        hibernate:
            ddl-auto: create-drop
